<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\MedicalDepartment;
use Illuminate\Database\Seeder;

class MedicalDepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departments = [
            [
                'name_en' => 'Internal Medicine',
                'name_ar' => 'الطب الباطني',
                'icon' => 'medical_services',
                'color' => '#2196F3',
                'relevant_categories' => ['Internal Medicine', 'General', 'Cardiology', 'Gastroenterology', 'Pulmonology', 'Nephrology'],
                'sort_order' => 1,
            ],
            [
                'name_en' => 'Cardiology',
                'name_ar' => 'أمراض القلب',
                'icon' => 'favorite',
                'color' => '#E53935',
                'relevant_categories' => ['Cardiology', 'Internal Medicine', 'General', 'ICU'],
                'sort_order' => 2,
            ],
            [
                'name_en' => 'Emergency Medicine',
                'name_ar' => 'طب الطوارئ',
                'icon' => 'emergency',
                'color' => '#FF5722',
                'relevant_categories' => ['Emergency', 'General', 'Trauma', 'ICU'],
                'sort_order' => 3,
            ],
            [
                'name_en' => 'General Surgery',
                'name_ar' => 'الجراحة العامة',
                'icon' => 'content_cut',
                'color' => '#607D8B',
                'relevant_categories' => ['Surgery', 'General Surgery', 'General', 'ICU'],
                'sort_order' => 4,
            ],
            [
                'name_en' => 'Orthopedics',
                'name_ar' => 'جراحة العظام',
                'icon' => 'accessibility_new',
                'color' => '#795548',
                'relevant_categories' => ['Orthopedics', 'Rehabilitation', 'General'],
                'sort_order' => 5,
            ],
            [
                'name_en' => 'Obstetrics & Gynecology',
                'name_ar' => 'النساء والتوليد',
                'icon' => 'pregnant_woman',
                'color' => '#E91E63',
                'relevant_categories' => ['Obstetrics', 'Gynecology', 'OB/GYN', 'General', 'NICU'],
                'sort_order' => 6,
            ],
            [
                'name_en' => 'Pediatrics',
                'name_ar' => 'طب الأطفال',
                'icon' => 'child_care',
                'color' => '#00BCD4',
                'relevant_categories' => ['Pediatrics', 'General', 'NICU'],
                'sort_order' => 7,
            ],
            [
                'name_en' => 'Ophthalmology',
                'name_ar' => 'طب العيون',
                'icon' => 'remove_red_eye',
                'color' => '#00897B',
                'relevant_categories' => ['Ophthalmology', 'General'],
                'sort_order' => 8,
            ],
            [
                'name_en' => 'ENT (Ear, Nose & Throat)',
                'name_ar' => 'الأنف والأذن والحنجرة',
                'icon' => 'hearing',
                'color' => '#5C6BC0',
                'relevant_categories' => ['ENT', 'General'],
                'sort_order' => 9,
            ],
            [
                'name_en' => 'Radiology',
                'name_ar' => 'الأشعة',
                'icon' => 'biotech',
                'color' => '#546E7A',
                'relevant_categories' => ['Radiology', 'General'],
                'sort_order' => 10,
            ],
            [
                'name_en' => 'Anesthesiology',
                'name_ar' => 'التخدير والإنعاش',
                'icon' => 'air',
                'color' => '#9575CD',
                'relevant_categories' => ['Anesthesiology', 'ICU', 'General'],
                'sort_order' => 11,
            ],
            [
                'name_en' => 'Psychiatry',
                'name_ar' => 'الطب النفسي',
                'icon' => 'psychology',
                'color' => '#7E57C2',
                'relevant_categories' => ['Psychiatry', 'Mental Health', 'General'],
                'sort_order' => 12,
            ],
            [
                'name_en' => 'Neurology',
                'name_ar' => 'أمراض الأعصاب',
                'icon' => 'memory',
                'color' => '#3F51B5',
                'relevant_categories' => ['Neurology', 'General', 'ICU'],
                'sort_order' => 13,
            ],
            [
                'name_en' => 'Neurosurgery',
                'name_ar' => 'جراحة الأعصاب',
                'icon' => 'account_tree',
                'color' => '#283593',
                'relevant_categories' => ['Neurosurgery', 'Surgery', 'ICU', 'General'],
                'sort_order' => 14,
            ],
            [
                'name_en' => 'Urology',
                'name_ar' => 'المسالك البولية',
                'icon' => 'water_drop',
                'color' => '#0288D1',
                'relevant_categories' => ['Urology', 'Surgery', 'General'],
                'sort_order' => 15,
            ],
            [
                'name_en' => 'Nephrology',
                'name_ar' => 'أمراض الكلى',
                'icon' => 'filter_alt',
                'color' => '#0097A7',
                'relevant_categories' => ['Nephrology', 'General', 'ICU'],
                'sort_order' => 16,
            ],
            [
                'name_en' => 'Gastroenterology',
                'name_ar' => 'أمراض الجهاز الهضمي',
                'icon' => 'restaurant',
                'color' => '#558B2F',
                'relevant_categories' => ['Gastroenterology', 'General'],
                'sort_order' => 17,
            ],
            [
                'name_en' => 'Pulmonology',
                'name_ar' => 'أمراض الرئة والجهاز التنفسي',
                'icon' => 'wind_power',
                'color' => '#039BE5',
                'relevant_categories' => ['Pulmonology', 'ICU', 'General'],
                'sort_order' => 18,
            ],
            [
                'name_en' => 'Endocrinology',
                'name_ar' => 'الغدد الصماء',
                'icon' => 'science',
                'color' => '#AD1457',
                'relevant_categories' => ['Endocrinology', 'Diabetes', 'General'],
                'sort_order' => 19,
            ],
            [
                'name_en' => 'Oncology',
                'name_ar' => 'الأورام',
                'icon' => 'coronavirus',
                'color' => '#6A1B9A',
                'relevant_categories' => ['Oncology', 'Palliative Care', 'General'],
                'sort_order' => 20,
            ],
            [
                'name_en' => 'Hematology',
                'name_ar' => 'أمراض الدم',
                'icon' => 'bloodtype',
                'color' => '#C62828',
                'relevant_categories' => ['Hematology', 'Oncology', 'General'],
                'sort_order' => 21,
            ],
            [
                'name_en' => 'Rheumatology',
                'name_ar' => 'أمراض الروماتيزم والمفاصل',
                'icon' => 'settings_accessibility',
                'color' => '#4E342E',
                'relevant_categories' => ['Rheumatology', 'General'],
                'sort_order' => 22,
            ],
            [
                'name_en' => 'Dermatology',
                'name_ar' => 'الجلدية',
                'icon' => 'face',
                'color' => '#FF7043',
                'relevant_categories' => ['Dermatology', 'General'],
                'sort_order' => 23,
            ],
            [
                'name_en' => 'Plastic Surgery',
                'name_ar' => 'جراحة التجميل',
                'icon' => 'auto_fix_high',
                'color' => '#F06292',
                'relevant_categories' => ['Plastic Surgery', 'Surgery', 'General'],
                'sort_order' => 24,
            ],
            [
                'name_en' => 'Vascular Surgery',
                'name_ar' => 'جراحة الأوعية الدموية',
                'icon' => 'linear_scale',
                'color' => '#D32F2F',
                'relevant_categories' => ['Vascular Surgery', 'Surgery', 'General'],
                'sort_order' => 25,
            ],
            [
                'name_en' => 'Cardiac Surgery',
                'name_ar' => 'جراحة القلب',
                'icon' => 'monitor_heart',
                'color' => '#B71C1C',
                'relevant_categories' => ['Cardiac Surgery', 'Cardiology', 'ICU', 'General'],
                'sort_order' => 26,
            ],
            [
                'name_en' => 'Thoracic Surgery',
                'name_ar' => 'جراحة الصدر',
                'icon' => 'airline_seat_recline_normal',
                'color' => '#37474F',
                'relevant_categories' => ['Thoracic Surgery', 'Surgery', 'ICU', 'General'],
                'sort_order' => 27,
            ],
            [
                'name_en' => 'Colorectal Surgery',
                'name_ar' => 'جراحة القولون والمستقيم',
                'icon' => 'loop',
                'color' => '#4CAF50',
                'relevant_categories' => ['Colorectal Surgery', 'Surgery', 'General'],
                'sort_order' => 28,
            ],
            [
                'name_en' => 'Hepatobiliary Surgery',
                'name_ar' => 'جراحة الكبد والمرارة',
                'icon' => 'manage_accounts',
                'color' => '#827717',
                'relevant_categories' => ['Hepatobiliary', 'Surgery', 'General'],
                'sort_order' => 29,
            ],
            [
                'name_en' => 'Transplant Surgery',
                'name_ar' => 'جراحة الزراعة',
                'icon' => 'swap_horiz',
                'color' => '#1B5E20',
                'relevant_categories' => ['Transplant', 'Surgery', 'ICU', 'General'],
                'sort_order' => 30,
            ],
            [
                'name_en' => 'Spine Surgery',
                'name_ar' => 'جراحة العمود الفقري',
                'icon' => 'straighten',
                'color' => '#263238',
                'relevant_categories' => ['Spine Surgery', 'Orthopedics', 'Surgery', 'General'],
                'sort_order' => 31,
            ],
            [
                'name_en' => 'Maxillofacial Surgery',
                'name_ar' => 'جراحة الفكوك والوجه',
                'icon' => 'face_retouching_natural',
                'color' => '#880E4F',
                'relevant_categories' => ['Maxillofacial', 'Surgery', 'General'],
                'sort_order' => 32,
            ],
            [
                'name_en' => 'Diabetes & Endocrine',
                'name_ar' => 'السكري والغدد',
                'icon' => 'monitor',
                'color' => '#1565C0',
                'relevant_categories' => ['Diabetes', 'Endocrinology', 'General'],
                'sort_order' => 33,
            ],
            [
                'name_en' => 'Infectious Disease',
                'name_ar' => 'الأمراض المعدية',
                'icon' => 'bug_report',
                'color' => '#33691E',
                'relevant_categories' => ['Infectious Disease', 'General', 'ICU'],
                'sort_order' => 34,
            ],
            [
                'name_en' => 'Allergy & Immunology',
                'name_ar' => 'الحساسية والمناعة',
                'icon' => 'shield',
                'color' => '#00695C',
                'relevant_categories' => ['Allergy', 'Immunology', 'General'],
                'sort_order' => 35,
            ],
            [
                'name_en' => 'Geriatrics',
                'name_ar' => 'طب المسنين',
                'icon' => 'elderly',
                'color' => '#78909C',
                'relevant_categories' => ['Geriatrics', 'Internal Medicine', 'General'],
                'sort_order' => 36,
            ],
            [
                'name_en' => 'Family Medicine & GP',
                'name_ar' => 'طب الأسرة والعيادة العامة',
                'icon' => 'home',
                'color' => '#43A047',
                'relevant_categories' => ['Family Medicine', 'General', 'Primary Care'],
                'sort_order' => 37,
            ],
            [
                'name_en' => 'Physical Medicine & Rehab',
                'name_ar' => 'الطب الطبيعي وإعادة التأهيل',
                'icon' => 'fitness_center',
                'color' => '#F57F17',
                'relevant_categories' => ['Rehabilitation', 'Physical Therapy', 'General'],
                'sort_order' => 38,
            ],
            [
                'name_en' => 'Clinical Nutrition',
                'name_ar' => 'التغذية الإكلينيكية',
                'icon' => 'restaurant_menu',
                'color' => '#689F38',
                'relevant_categories' => ['Nutrition', 'General'],
                'sort_order' => 39,
            ],
            [
                'name_en' => 'Pathology & Lab Medicine',
                'name_ar' => 'علم الأمراض والمختبر',
                'icon' => 'colorize',
                'color' => '#4527A0',
                'relevant_categories' => ['Pathology', 'Laboratory', 'General'],
                'sort_order' => 40,
            ],
            [
                'name_en' => 'Nuclear Medicine',
                'name_ar' => 'الطب النووي',
                'icon' => 'energy_savings_leaf',
                'color' => '#00838F',
                'relevant_categories' => ['Nuclear Medicine', 'Radiology', 'General'],
                'sort_order' => 41,
            ],
            [
                'name_en' => 'Interventional Radiology',
                'name_ar' => 'الأشعة التداخلية',
                'icon' => 'radar',
                'color' => '#455A64',
                'relevant_categories' => ['Interventional Radiology', 'Radiology', 'General'],
                'sort_order' => 42,
            ],
            [
                'name_en' => 'Palliative Care',
                'name_ar' => 'الرعاية التلطيفية',
                'icon' => 'spa',
                'color' => '#6D4C41',
                'relevant_categories' => ['Palliative Care', 'Oncology', 'General'],
                'sort_order' => 43,
            ],
            [
                'name_en' => 'Sports Medicine',
                'name_ar' => 'الطب الرياضي',
                'icon' => 'sports',
                'color' => '#00897B',
                'relevant_categories' => ['Sports Medicine', 'Orthopedics', 'General'],
                'sort_order' => 44,
            ],
            [
                'name_en' => 'Occupational Medicine',
                'name_ar' => 'طب العمل والمهن',
                'icon' => 'work',
                'color' => '#37474F',
                'relevant_categories' => ['Occupational Medicine', 'General'],
                'sort_order' => 45,
            ],
            [
                'name_en' => 'Intensive Care / ICU',
                'name_ar' => 'العناية المركزة',
                'icon' => 'monitor_heart',
                'color' => '#BF360C',
                'relevant_categories' => ['ICU', 'Critical Care', 'General', 'Cardiology', 'Pulmonology'],
                'sort_order' => 46,
            ],
            [
                'name_en' => 'Neonatology (NICU)',
                'name_ar' => 'حديثو الولادة',
                'icon' => 'baby_changing_station',
                'color' => '#EC407A',
                'relevant_categories' => ['NICU', 'Neonatology', 'Pediatrics', 'General'],
                'sort_order' => 47,
            ],
            [
                'name_en' => 'Dentistry',
                'name_ar' => 'طب الأسنان',
                'icon' => 'medical_information',
                'color' => '#29B6F6',
                'relevant_categories' => ['Dentistry', 'General'],
                'sort_order' => 48,
            ],
            [
                'name_en' => 'Alternative Medicine',
                'name_ar' => 'الطب البديل والتكميلي',
                'icon' => 'local_florist',
                'color' => '#66BB6A',
                'relevant_categories' => ['Alternative Medicine', 'General'],
                'sort_order' => 49,
            ],
            [
                'name_en' => 'Insurance',
                'name_ar' => 'التأمين الصحي',
                'icon' => 'verified_user',
                'color' => '#0277BD',
                'relevant_categories' => ['Insurance', 'General'],
                'sort_order' => 50,
            ],
            [
                'name_en' => 'Nursing',
                'name_ar' => 'التمريض',
                'icon' => 'health_and_safety',
                'color' => '#00ACC1',
                'relevant_categories' => ['Nursing', 'General'],
                'sort_order' => 51,
            ],
        ];

        foreach ($departments as $department) {
            MedicalDepartment::updateOrCreate(
                ['name_en' => $department['name_en']],
                $department
            );
        }
    }
}
