<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;

class OciGenerativeAiService extends OciBaseService
{
    // ── SINGLE PINNED MODEL (reproducibility + data-sovereignty policy) ──
    // A medical scribe MUST produce the same structured note for the same
    // dictation every time. The deterministic safety nets (numeric, entity,
    // critical-term, polarity) and the strict JSON-envelope contract in
    // TextAnalysisService are all tuned against ONE model's behaviour. Silently
    // switching to a different model — with different JSON, acronym, and
    // formatting conventions — would make the output non-reproducible and
    // unauditable, which is unacceptable for clinical documentation. We
    // therefore pin exactly one model and, if it is unavailable, fail LOUD so
    // the doctor sees a clear error instead of a note quietly produced by a
    // different model. Ops can still override via the OCI_GENERATIVE_AI_MODEL
    // env var (resolved through config), but there is NO multi-model failover.
    public const PRIMARY_MODEL = 'cohere.command-a-03-2025';

    public function generate(string $prompt, ?string $model = null, float $temperature = 0.7, int $maxTokens = 2000): array
    {
        // Resolution order: explicit arg > configured/env model > pinned default.
        // Exactly one model is ever attempted — no fallback chain.
        $modelId = $model
            ?: ($this->config['generative_ai_model'] ?? null)
            ?: self::PRIMARY_MODEL;

        try {
            Log::debug("Using pinned OCI model: {$modelId}");
            $t0 = microtime(true);
            $result = $this->generateWithModel($prompt, $modelId, $temperature, $maxTokens);
            $ms = (int) round((microtime(true) - $t0) * 1000);
            Log::info("OCI model succeeded", ['model' => $modelId, 'ms' => $ms]);
            return $result;
        } catch (\Exception $e) {
            // No silent cross-model failover: surface the failure so the caller
            // (and ultimately the doctor) knows the pinned model was unavailable
            // rather than trusting a note generated by some other model.
            Log::error("OCI pinned model failed — no fallback (single-model policy)", [
                'model' => $modelId,
                'error' => $e->getMessage(),
            ]);
            throw new \Exception("OCI Generative AI model '{$modelId}' is unavailable: " . $e->getMessage(), 0, $e);
        }
    }

    private function generateWithModel(string $prompt, string $modelId, float $temperature, int $maxTokens): array
    {
        $region = $this->config['region'] ?? 'me-riyadh-1';
        $compartmentId = $this->config['compartment_id'];

        $url = "https://inference.generativeai.{$region}.oci.oraclecloud.com/20231130/actions/chat";

        $apiFormat = 'COHERE';
        $modelIdLower = strtolower($modelId);
        if (str_contains($modelIdLower, 'llama') || str_contains($modelIdLower, 'meta') || str_contains($modelIdLower, 'gemini') || str_contains($modelIdLower, 'grok')) {
            $apiFormat = 'GENERIC';
        }

        $chatRequest = [
            'apiFormat' => $apiFormat,
            'maxTokens' => $maxTokens,
            'temperature' => $temperature,
            'isStream' => false,
        ];

        if ($apiFormat === 'COHERE') {
            $chatRequest['message'] = $prompt;
        } else {
            $chatRequest['messages'] = [
                [
                    'role' => 'USER',
                    'content' => [
                        [
                            'type' => 'TEXT',
                            'text' => $prompt
                        ]
                    ]
                ]
            ];
        }

        $body = json_encode([
            'compartmentId' => $compartmentId,
            'servingMode' => [
                'servingType' => 'ON_DEMAND',
                'modelId' => $modelId,
            ],
            'chatRequest' => $chatRequest,
        ]);

        $response = $this->makeRequest('POST', $url, $body, [
            'content-type' => 'application/json',
        ]);

        $data = $response['json'];

        $generatedText = '';
        if ($apiFormat === 'COHERE') {
            $generatedText = $data['chatResponse']['text'] ?? '';
        } else {
            $choices = $data['chatResponse']['choices'] ?? [];
            if (!empty($choices)) {
                $generatedText = $choices[0]['message']['content'][0]['text'] ?? '';
            }
        }

        return [
            'text' => trim($generatedText),
            'model' => $modelId,
            'source' => 'oci',
            'raw' => $data,
        ];
    }
}
